### PR TITLE
Upgrade to Fisher 4.x

### PR DESCRIPTION
**Pull request by kidonng**
This PR adds support for Fisher 4.0.

I'm basically replicating https://github.com/jorgebucaran/nvm.fish/commit/b5811897fd3feb0e2d1adabf314a4191ad103da2 and https://github.com/jorgebucaran/gitfu.fish/commit/2aaca11d9240b3648b65f05b8b326177d6b0aad3. Doesn't know if this meets your standard, but I hope you like it :)

(Tests doesn't work autoload yet :()

### CODE REVIEW

**Comment by kidonng** [comment]
Never mind, I guess you are gonna rewrite it.

**Comment by jorgebucaran** [comment]
@kidonng We can merge here if you revert the version number (since it won't change until everything it's properly done) and change the commit name to "Fisher 4.x support" or something like that.

**Comment by kidonng** [comment]
@jorgebucaran That's good to hear!

**Comment by jorgebucaran** [comment]
Thank you, @kidonng!

**Pull request merged**
